version: "3.9"
services:
  zookeeper:
    image: "zookeeper:3.7.0"
    restart: unless-stopped
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/data
      - zookeeper_log:/datalog
  zoonavigator:
    image: "elkozmon/zoonavigator:1.1.0"
    restart: unless-stopped
    ports:
      - "1812:9000"
    environment:
      HTTP_PORT: 9000
  kafka:
    image: "bitnami/kafka:2.8.0"
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - kafka:/bitnami/kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
  kafkamanager:
    image: "deltaprojects/kafka-manager:v3.0.0.5-2"
    restart: unless-stopped
    ports:
      - "2909:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin
  etcd:
   image: "bitnami/etcd:3.5.0"
   restart: unless-stopped
   ports:
     - "2379:2379"
     - "2380:2380"
   volumes:
     - etcd:/opt/bitnami
   environment:
     ALLOW_NONE_AUTHENTICATION: "yes"
     ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
  etcdkeeper:
    image: "deltaprojects/etcdkeeper:latest"
    restart: unless-stopped
    ports:
      - "8081:8080"
volumes:
  kafka:
  etcd:
  zookeeper:
  zookeeper_log:
